### ISSUE TITLE
cannot `list_cameras` because udev is not supported in docker

### ISSUE THREAD

**Issue by waspinator** [ros-drivers/pointgrey_camera_driver#96]
I'm trying to use docker with ROS, and I'm having trouble listing cameras because it appears to require udev. Is there a way I can use this package with Docker?

Thanks

**Comment by adamreis** [comment]
@waspinator I'm running into the same problem. Did you have any luck getting this working?

**Comment by mikepurvis** [comment]
Docker is isolated from hardware by design. Does it work if you mount the udev path inside the container? (eg, `-v /run/udev:/run/udev:ro`)

**Comment by adamreis** [comment]
@mikepurvis thanks for following up on this. I'm pursuing another path, because I need to use Spinnaker with my Blackfly S, but I'll definitely give that a try and report back if I end up using this project.

**Comment by waspinator** [comment]
@adamreis how do you plan on using Spinnaker with ROS?

**Comment by vik748** [comment]
Anyone have any experience making Spinnaker work with ROS.  We have been trying for a while but seem to keep getting Segmentation Faults originating in the Spinnaker library when trying to instantiate Image Transport.  Our investigation shows that this is due to some conflict in Boost that both Spinnaker and Image Transport use.  GDB shows error coming from the Spinnaker Library.  If anyone has experience something similar or found a work around, please do share.
BTW we are trying to use the Blackfly S cameras.

**Comment by mikepurvis** [comment]
@vik748 The Spinnaker so bundles in boost and a bunch of stuff, so I could totally imagine getting a bunch of weird symbol conflicts. A new spinnaker driver might need to run that in a separate process and pass images across shared memory to ROS. I'm not sure.

In any case, please don't resurrect this unrelated issue. If you'd like to discuss further, open a new one.
